server:
  port: 10003
spring:
  application:
    name: service-session-zuul
zuul:
  ignoredServices: '*' #忽略所有未配置的service
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    redis-session-service:
      path: /user-session/**
      serviceId: service-session-redis
      sensitiveHeaders: "*"
ribbon: #ribbon负载均衡参数配置
  ReadTimeout: 5000
  ConnectTimeout: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/