server:
  port: 80
  servlet:
    session:
      timeout: 5s
spring:
  profiles:
    active: product
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.h2/testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/static/,classpath:/static/,classpath:/public
